---
name: "Valgrind"

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.wordlist.txt'

env:
  CARGO_TERM_COLOR: always

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup toolchain (coverage)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - name: Run tests (memory safety)
        continue-on-error: true
        run: |
          sudo apt install -y valgrind
          cargo install cargo-valgrind
          cargo valgrind test --verbose
